[mypy]
python_version = 3.11
strict = True
ignore_missing_imports = True
exclude = ["venv", ".venv", "tests"]

[mypy-mlxtend.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True
